# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestingFramwork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestingFramwork
    pod "SASFramework", :path => "/Users/sukumaranupsukumaran/Desktop/Framework/SASFramework/SASFramework"

  target 'TestingFramworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestingFramworkUITests' do
    # Pods for testing
  end

end
